### PR TITLE
chore: appease black on ergo/schematic.py

### PR DESCRIPTION
**Pull request by xytxytxyt**
ergo==0.9.1 did not deploy; i'm taking a wild guess that this is the reason

### CODE REVIEW

**Comment by xytxytxyt** [comment]
it seems pep8 and black disagree: 
[black](https://app.circleci.com/pipelines/github/nautiluslabsco/ergo/929/workflows/18f04dce-4deb-4802-bd5a-c1bb875e9a46/jobs/2756): 
image

[pep8](https://app.circleci.com/pipelines/github/nautiluslabsco/ergo/931/workflows/a09f3d2f-bbfe-4124-97e4-e4a69dc50f35/jobs/2758):
image

anyway my original problem is that 0.9.1 did not seem to be deployed and i'm trying to debug why...

**Comment by xytxytxyt** [comment]
i know i can just massage the code to not trigger this conundrum but does black really have that much power over me?

**Comment by xytxytxyt** [comment]
since i named my pr 'appease black' maybe deep down i already know the answer...

**Comment by zekenautilus** [comment]
@xytxytxyt so weird that the linting issue got caught on master, but on your test branch...

**Review by zekenautilus — APPROVED** [review]
👍 still curious if there isn't a way to configure black / pep8 to be compliant with each other.

~I also think we installed black on this repo back when it was in alpha - it's since had an official release and maybe if we upgrade it'll behave better?~

**Pull request merged**
